// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwGW7gLfaj1dXvTkZJwaAUECFy_kgKvF0',
    appId: '1:480827857489:web:757665d12ff5e5b9273670',
    messagingSenderId: '480827857489',
    projectId: 'football-tips-72b60',
    authDomain: 'football-tips-72b60.firebaseapp.com',
    storageBucket: 'football-tips-72b60.firebasestorage.app',
    measurementId: 'G-B0N9S5TEPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTpkrh9BeLzdbBCME8Yt4JEJpR4G9s9EQ',
    appId: '1:480827857489:android:1036378f0ff24565273670',
    messagingSenderId: '480827857489',
    projectId: 'football-tips-72b60',
    storageBucket: 'football-tips-72b60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuUr9SNklKI7aBXTwZ2Cpehtr4FNKWjfk',
    appId: '1:480827857489:ios:b14ac48aec479f2b273670',
    messagingSenderId: '480827857489',
    projectId: 'football-tips-72b60',
    storageBucket: 'football-tips-72b60.firebasestorage.app',
    iosBundleId: 'com.example.footballTips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuUr9SNklKI7aBXTwZ2Cpehtr4FNKWjfk',
    appId: '1:480827857489:ios:b14ac48aec479f2b273670',
    messagingSenderId: '480827857489',
    projectId: 'football-tips-72b60',
    storageBucket: 'football-tips-72b60.firebasestorage.app',
    iosBundleId: 'com.example.footballTips',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwGW7gLfaj1dXvTkZJwaAUECFy_kgKvF0',
    appId: '1:480827857489:web:7aa5560b13adb072273670',
    messagingSenderId: '480827857489',
    projectId: 'football-tips-72b60',
    authDomain: 'football-tips-72b60.firebaseapp.com',
    storageBucket: 'football-tips-72b60.firebasestorage.app',
    measurementId: 'G-PWDW3FP80W',
  );

}